[tox]
envlist = py39, py310, py311, py312, py313

[testenv]
# Call extras_require from setup (test deps)
extras = test
setenv =
    PYTHONPATH = {toxinidir}
deps =
	coverage
	pytest-cov
commands = pytest tests
