#channels:
#  - conda-forge
dependencies:
    - python>=3.5
    #- sphinx>=1.4  # Get WIP version of sphinx with MD stuff
    - pip
    - pandoc
    - nbconvert
    - ipykernel
    - pip:
          - sphinx
          - nbsphinx
          - sphinx-gallery
          - sphinx-copybutton
          - recommonmark
          - m2r
