#channels:
#  - conda-forge
dependencies:
  - python>=3.5
  #- sphinx>=1.4  # Get WIP version of sphinx with MD stuff
  - pip
  - pandoc
  - nbconvert
  - ipykernel
  - pip:
    - sphinx
    - git+git://github.com/mgeier/nbsphinx.git@master  # Do change that when this is merged (https://github.com/spatialaudio/nbsphinx/pull/463)
    #- sphinx-nbexamples
    - git+https://github.com/Chilipp/sphinx-nbexamples.git@master # Use app.add_css_file for sphinx >= 3.0, change when https://github.com/Chilipp/sphinx-nbexamples is released
    - sphinx-gallery
    - sphinx-copybutton
    - recommonmark
    - m2r
