on:
  push:
    paths:
      - README.Rmd

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install Core Dependencies
        run: Rscript -e 'install.packages(c("rmarkdown", "dplyr", "remotes"))'
      - name: Install Python
        run: |
            Rscript -e "remotes::install_github('rstudio/reticulate')"
            Rscript -e "reticulate::install_miniconda()"
            Rscript -e "reticulate::py_install(c('Pillow', 'scipy'), pip = TRUE)"
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Commit results
        run: |
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
